# Generated by Django 5.1.7 on 2025-03-29 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Ahafo Region', 'Goaso'), ('Ashanti Region', 'Kumasi'), ('Bono Region', 'Sunyani'), ('Bono East Region', 'Techiman'), ('Central Region', 'Cape Coast'), ('Eastern Region', 'Koforidua'), ('Greater Accra Region', 'Accra'), ('North East Region', 'Nalerigu'), ('Northern Region', 'Tamale'), ('Oti Region', 'Dambai'), ('Savannah Region', 'Damongo'), ('Upper East Region', 'Bolgatanga'), ('Upper West Region', 'Wa'), ('Volta Region', 'Ho'), ('Western Region', ' Sekondi-Takoradi'), ('Western North Region', ' Sefwi Wiawso')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
